### PR TITLE
Pin gitleaks to v1 as v2 needs a paid API token

### PR DESCRIPTION
**Pull request by jhkennedy**
See: https://github.com/gitleaks/gitleaks-action#-announcement

### CODE REVIEW

**Review by asjohnston-asf — APPROVED** [review]

**Comment by cmarshak** [comment]
How do I update existing actions to not fail? I am simply "re-running" jobs. Do I need to update the action itself?

**Comment by jhkennedy** [comment]
@cmarshak if the action's already been run, re-running all failed jobs should do it

**Comment by cmarshak** [comment]
I tried here: https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/actions/runs/2579842974

Seems to still request the license.

**Comment by jhkennedy** [comment]
@cmarshak weird -- it's still using the older action, not what's on main:
https://github.com/ASFHyP3/actions/blob/main/.github/workflows/reusable-secrets-analysis.yml#L13

**Comment by cmarshak** [comment]
For what it's worth, I just did a recent push and the gitleaks passed: https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/runs/7117109359?check_suite_focus=true

I think it must freeze the action version at the time of commit. Just a guess.

**Pull request merged**
